## config.toml
## Example replication-manager configuration file

## change the service file  in /etc/systemd/system/replication-manager.service to looks like :
## replication-manager-osc  --config=./etc/config.toml.sample  --cluster=Cluster01,Cluster_Test_2_Nodes monitor

[MultiMasterProxysql]
title = "MultiMasterProxysql"

prov-orchestrator = "local"
db-servers-hosts = "127.0.0.1:3313,127.0.0.1:3314"
db-servers-prefered-master = "127.0.0.1:3313"
db-servers-credential = "root:mariadb"
db-servers-connect-timeout = 1

replication-credential = "root:mariadb"
replication-multi-master = true

failover-readonly-state = false
force-slave-readonly = false

proxy-servers-read-on-master = true

proxysql = true
proxysql-servers = "127.0.0.1"
proxysql-user = "admin"
proxysql-password = "admin"
proxysql-port = "3306"
proxysql-admin-port = "6032"


proxysql-bootstrap = true
proxysql-bootstrap-query-rules = true
proxysql-bootstrap-users = true
proxysql-bootstrap-variables = true
proxysql-bootstrap-hostgroups = false
proxysql-save-to-disk = true


